### ISSUE TITLE
CMake 3.16 or higher is required.  You are running version 3.5.1

### ISSUE THREAD

**Issue by saha007** [chrvadala/potree-converter-docker#3]
Configuring incomplete, errors occurred!

CmakeList of https://github.com/potree/PotreeConverter.git requires Cmake VERSION [3.16 cmake_minimum_required(VERSION 3.16)].
Getting "ERROR [5/6] RUN git clone -b develop https://github.com/potree/PotreeConverter.git && cd PotreeConverter && mkdir build && cd bu...." every time while trying to build image on VS code.

**Comment by Takieddinex** [comment]
@saha007 i have the same errors, did you find the way to do it please ?

**Comment by chrvadala** [comment]
It should be fixed with https://github.com/chrvadala/potree-converter-docker/pull/4
